from typing import Dict, Optional, Iterator
import numpy as np

class LoaderConfig:
    """Configuration for the veldt Loader."""
    def __init__(
        self,
        *,
        batch_size: int = 32,
        num_decode_threads: int = 0,
        buffer_size: int = 10_000,
        prefetch_depth: int = 64,
        width: int = 224,
        height: int = 224,
        normalize: bool = False,
        mean: tuple[float, float, float] = (0.485, 0.456, 0.406),
        std: tuple[float, float, float] = (0.229, 0.224, 0.225),
    ) -> None: ...

class Batch:
    """A batch of training samples."""
    @property
    def frames(self) -> np.ndarray: ...
    @property
    def batch_size(self) -> int: ...
    def tabular(self, key: str) -> Optional[np.ndarray]: ...
    def keys(self) -> list[str]: ...

class Loader:
    """Seek-optimized video data loader."""
    def __init__(self, dataset_path: str, config: Optional[LoaderConfig] = None) -> None: ...
    def set_epoch(self, epoch: int, seed: int = 42) -> None: ...
    def __iter__(self) -> Iterator[Batch]: ...
    def __next__(self) -> Batch: ...
    def __len__(self) -> int: ...
    def stats(self) -> Dict[str, int]: ...
    def metadata(self) -> Dict[str, object]: ...
